// Public contract pinned by this acceptance test:
//
//     pub struct RecurrenceSplit {
//         /// The original master rule, replaced by a finite rule containing
//         /// exactly the occurrences before the selected instance.
//         pub original_recurrence: RecurrenceSpec,
//         /// The selected occurrence's schedule, retaining the original
//         /// duration and (for timed events) its TZID-local wall-clock time.
//         pub future_schedule: EventSchedule,
//         /// The future master rule, whose first occurrence is the selected
//         /// instance and whose remaining end condition is preserved.
//         pub future_recurrence: RecurrenceSpec,
//     }
//     pub enum RecurrenceSplitError { ... }
//     pub fn split_recurrence_at(
//         master: &Event,
//         recurrence_id: &RecurrenceId,
//     ) -> Result<RecurrenceSplit, RecurrenceSplitError>;
//
// This is deliberately a GTK-free, pure operation. It never mutates `master`.

use calendar::model::{Event, EventSchedule, RecurrenceId, RecurrenceSpec};
use calendar::recurrence_form::{RecurrenceSplit, RecurrenceSplitError, split_recurrence_at};
use chrono::{DateTime, NaiveDate};
use uuid::Uuid;

fn date(year: i32, month: u32, day: u32) -> NaiveDate {
    NaiveDate::from_ymd_opt(year, month, day).unwrap()
}

fn all_day_master(start: NaiveDate, end: NaiveDate, rule: &str) -> Event {
    Event {
        id: Uuid::parse_str("11111111-1111-1111-1111-111111111111").unwrap(),
        calendar_id: Uuid::parse_str("22222222-2222-2222-2222-222222222222").unwrap(),
        title: "Series".to_owned(),
        location: String::new(),
        description: String::new(),
        schedule: EventSchedule::AllDay {
            start_date: start,
            end_date_exclusive: end,
        },
        recurrence: Some(RecurrenceSpec {
            rrule: vec![rule.to_owned()],
            rdate: Vec::new(),
            exdate: Vec::new(),
        }),
        reminders: Vec::new(),
    }
}

#[test]
fn phase2c_splits_only_generated_simple_occurrences_without_changing_the_master() {
    // COUNT is partitioned, with the selected third daily occurrence becoming
    // the first of the future master. The all-day two-day duration is retained.
    let counted = all_day_master(
        date(2026, 7, 1),
        date(2026, 7, 3),
        "RRULE:FREQ=DAILY;COUNT=5",
    );
    let split: Result<RecurrenceSplit, RecurrenceSplitError> =
        split_recurrence_at(&counted, &RecurrenceId::AllDay(date(2026, 7, 3)));
    let split = split.expect("the third generated occurrence is splittable");
    assert_eq!(
        split.original_recurrence.rrule,
        vec!["RRULE:FREQ=DAILY;COUNT=2"],
        "the past side contains exactly the two occurrences before the split"
    );
    assert_eq!(
        split.future_schedule,
        EventSchedule::AllDay {
            start_date: date(2026, 7, 3),
            end_date_exclusive: date(2026, 7, 5),
        },
        "the future schedule starts at the selected identity and keeps the duration"
    );
    assert_eq!(
        split.future_recurrence.rrule,
        vec!["RRULE:FREQ=DAILY;COUNT=3"],
        "past and future COUNT values partition the original count"
    );
    assert_eq!(
        counted.recurrence.as_ref().unwrap().rrule[0],
        "RRULE:FREQ=DAILY;COUNT=5"
    );

    // A weekly INTERVAL/BYDAY rule counts actual generated instances, not
    // calendar weeks: Jul 6, Jul 8, Jul 20 is the third generated occurrence.
    let weekly = all_day_master(
        date(2026, 7, 6),
        date(2026, 7, 7),
        "RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE;COUNT=6",
    );
    let weekly_split = split_recurrence_at(&weekly, &RecurrenceId::AllDay(date(2026, 7, 20)))
        .expect("a generated BYDAY occurrence after the first is splittable");
    assert_eq!(
        weekly_split.original_recurrence.rrule,
        vec!["RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE;COUNT=2"]
    );
    assert_eq!(
        weekly_split.future_recurrence.rrule,
        vec!["RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE;COUNT=4"]
    );

    // An UNTIL series gives the past a finite COUNT while preserving UNTIL on
    // the future side. Monthly and yearly simple rules follow the same rule.
    for (master, selected, expected_past, expected_future) in [
        (
            all_day_master(
                date(2026, 7, 1),
                date(2026, 7, 2),
                "RRULE:FREQ=DAILY;UNTIL=20260705",
            ),
            date(2026, 7, 3),
            "RRULE:FREQ=DAILY;COUNT=2",
            "RRULE:FREQ=DAILY;UNTIL=20260705",
        ),
        (
            all_day_master(
                date(2026, 1, 15),
                date(2026, 1, 16),
                "RRULE:FREQ=MONTHLY;COUNT=4",
            ),
            date(2026, 3, 15),
            "RRULE:FREQ=MONTHLY;COUNT=2",
            "RRULE:FREQ=MONTHLY;COUNT=2",
        ),
        (
            all_day_master(
                date(2024, 2, 29),
                date(2024, 3, 1),
                "RRULE:FREQ=YEARLY;COUNT=3",
            ),
            date(2028, 2, 29),
            "RRULE:FREQ=YEARLY;COUNT=1",
            "RRULE:FREQ=YEARLY;COUNT=2",
        ),
    ] {
        let split = split_recurrence_at(&master, &RecurrenceId::AllDay(selected))
            .expect("a generated simple occurrence is splittable");
        assert_eq!(split.original_recurrence.rrule, vec![expected_past]);
        assert_eq!(split.future_recurrence.rrule, vec![expected_future]);
    }

    // A TZID series crosses into CEST. The future event must use the selected
    // local 09:00 start and retain its one-hour duration, rather than adding a
    // fixed UTC weekly duration.
    let timed = Event {
        schedule: EventSchedule::Timed {
            start: DateTime::parse_from_rfc3339("2026-03-23T09:00:00+01:00").unwrap(),
            end: DateTime::parse_from_rfc3339("2026-03-23T10:00:00+01:00").unwrap(),
            timezone: Some("Europe/Berlin".to_owned()),
        },
        recurrence: Some(RecurrenceSpec {
            rrule: vec!["RRULE:FREQ=WEEKLY".to_owned()],
            rdate: Vec::new(),
            exdate: Vec::new(),
        }),
        ..all_day_master(date(2026, 1, 1), date(2026, 1, 2), "RRULE:FREQ=DAILY")
    };
    let timed_split = split_recurrence_at(
        &timed,
        &RecurrenceId::Timed {
            date_time: DateTime::parse_from_rfc3339("2026-03-30T09:00:00+02:00").unwrap(),
            timezone: Some("Europe/Berlin".to_owned()),
        },
    )
    .expect("a generated TZID occurrence after the DST transition is splittable");
    assert_eq!(
        timed_split.original_recurrence.rrule,
        vec!["RRULE:FREQ=WEEKLY;COUNT=1"]
    );
    assert_eq!(
        timed_split.future_recurrence.rrule,
        vec!["RRULE:FREQ=WEEKLY"]
    );
    assert_eq!(
        timed_split.future_schedule,
        EventSchedule::Timed {
            start: DateTime::parse_from_rfc3339("2026-03-30T09:00:00+02:00").unwrap(),
            end: DateTime::parse_from_rfc3339("2026-03-30T10:00:00+02:00").unwrap(),
            timezone: Some("Europe/Berlin".to_owned()),
        }
    );

    // Unsupported recurrence shapes and identities cannot be split, and every
    // rejection leaves the caller-owned master untouched.
    let invalid_cases = [
        (
            all_day_master(
                date(2026, 7, 1),
                date(2026, 7, 2),
                "RRULE:FREQ=DAILY;COUNT=4",
            ),
            RecurrenceId::AllDay(date(2026, 7, 1)),
        ),
        (
            all_day_master(
                date(2026, 7, 1),
                date(2026, 7, 2),
                "RRULE:FREQ=DAILY;INTERVAL=2",
            ),
            RecurrenceId::AllDay(date(2026, 7, 2)),
        ),
        (
            all_day_master(date(2026, 7, 1), date(2026, 7, 2), "RRULE:FREQ=DAILY"),
            RecurrenceId::Timed {
                date_time: DateTime::parse_from_rfc3339("2026-07-02T00:00:00+00:00").unwrap(),
                timezone: None,
            },
        ),
    ];
    for (master, identity) in invalid_cases {
        let before = master.clone();
        assert!(split_recurrence_at(&master, &identity).is_err());
        assert_eq!(
            master, before,
            "a rejected split must not mutate the master"
        );
    }
    let mut rdate = all_day_master(date(2026, 7, 1), date(2026, 7, 2), "RRULE:FREQ=DAILY");
    rdate.recurrence.as_mut().unwrap().rdate = vec!["RDATE;VALUE=DATE:20260710".to_owned()];
    let mut exdate = all_day_master(date(2026, 7, 1), date(2026, 7, 2), "RRULE:FREQ=DAILY");
    exdate.recurrence.as_mut().unwrap().exdate = vec!["EXDATE;VALUE=DATE:20260702".to_owned()];
    let multiple = Event {
        recurrence: Some(RecurrenceSpec {
            rrule: vec![
                "RRULE:FREQ=DAILY".to_owned(),
                "RRULE:FREQ=WEEKLY".to_owned(),
            ],
            rdate: Vec::new(),
            exdate: Vec::new(),
        }),
        ..rdate.clone()
    };
    let unsupported = all_day_master(
        date(2026, 7, 1),
        date(2026, 7, 2),
        "RRULE:FREQ=DAILY;BYMONTH=7",
    );
    for master in [rdate, exdate, multiple, unsupported] {
        let before = master.clone();
        assert!(split_recurrence_at(&master, &RecurrenceId::AllDay(date(2026, 7, 3))).is_err());
        assert_eq!(master, before);
    }
    let before = timed.clone();
    assert!(
        split_recurrence_at(
            &timed,
            &RecurrenceId::Timed {
                date_time: DateTime::parse_from_rfc3339("2026-03-30T09:00:00+02:00").unwrap(),
                timezone: Some("America/New_York".to_owned()),
            },
        )
        .is_err()
    );
    assert_eq!(timed, before, "a TZID mismatch must not mutate the master");
}
